<a href="https://colab.research.google.com/github/Pathin220/4105_ML/blob/main/4105_Hw_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
import torch
import tensorflow
import matplotlib.pyplot as plt
import numpy as np
import torch.nn as nn
import torch.optim as optim

In [113]:
#1. In our temperature prediction example, let’s change our model to a nonlinear system. Consider the following description for our model:

#w2 * t_u ** 2 + w1 * t_u + b.

#1.a Modify the training loop properly to accommodate this redefinition.

#1.b Use 5000 epochs for your training. Explore different learning rates from 0.1 to 0.0001 (you need four separate trainings).
#Report your loss for every 500 epochs per training.

#1.c Pick the best non-linear model and compare your final best loss against the linear model that we did during the lecture.
#For this, visualize the non-linear model against the linear model over the input dataset, as we did during the lecture. Is the actual result better or worse than our baseline linear model?

In [114]:
#setting values in array for X which is t_C and Y which is t_U
t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)
t_un = 0.1 * t_u

In [115]:
print(t_c)
print(t_u)


tensor([ 0.5000, 14.0000, 15.0000, 28.0000, 11.0000,  8.0000,  3.0000, -4.0000,
         6.0000, 13.0000, 21.0000])
tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000,
        48.4000, 60.4000, 68.4000])


In [116]:
#defining the nonlinear model
def nonlin_model(t_u, w2, w1, b):
    return w2 * t_u**2 + w1 * t_u + b

In [117]:
#defining the linear model
def lin_model(t_u, w, b):
    return w * t_u + b

In [118]:
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

In [119]:

w2 = torch.ones(())
w1 = torch.ones(())
b = torch.zeros(())

t_p = nonlin_model(t_u, w2, w1, b)
t_p

tensor([1310.1901, 3180.7100, 3445.4399, 6789.5103, 3225.9900, 2440.1101,
        1183.1101,  497.0399, 2390.9600, 3708.5601, 4746.9600])

In [120]:
#computing the loss
loss = loss_fn(t_p, t_c)
loss


tensor(11709471.)

In [121]:
# Non-linear training loop
def training_loop (n_epochs, optimizer, params, t_u, t_c, learning_rate):
    print(f'Learning Rate: {learning_rate}')
    for epoch in range(1, n_epochs+1):
        w1, w2, b = params
        t_p = nonlin_model (t_u, w1, w2, b)
        loss = loss_fn(t_p, t_c)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if epoch % 500 == 0:
            print ('Epoch %d, Loss %f' % (epoch, float(loss)))
    return params, loss

In [122]:
# Linear training loop
def lin_training_loop (n_epochs, optimizer, params, t_u, t_c):
    for epoch in range(1, n_epochs+1):
        t_p = lin_model (t_u, *params)
        loss = loss_fn(t_p, t_c)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if epoch % 500 == 0:
            print ('Epoch %d, Loss %f' % (epoch, float(loss)))
    return params, loss

In [123]:
learning_rate = [0.1, 0.01, 0.001, 0.0001]
train_params = torch.zeros(len(learning_rate), 3)
train_loss = torch.zeros(len(learning_rate), 1)
linear_train_params = torch.zeros(1, 2)
linear_train_loss = torch.zeros(1, 1)



In [124]:
for i in learning_rate:
    params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
    optimizer = optim.SGD([params], lr=i)

    train_params[learning_rate.index(i)], train_loss[learning_rate.index(i)] = training_loop(
        n_epochs = 5000,
        optimizer = optimizer,
        params = params,
        t_u = t_un,
        t_c = t_c,
        learning_rate = i
        )

Learning Rate: 0.1
Epoch 500, Loss nan
Epoch 1000, Loss nan
Epoch 1500, Loss nan
Epoch 2000, Loss nan
Epoch 2500, Loss nan
Epoch 3000, Loss nan
Epoch 3500, Loss nan
Epoch 4000, Loss nan
Epoch 4500, Loss nan
Epoch 5000, Loss nan
Learning Rate: 0.01
Epoch 500, Loss nan
Epoch 1000, Loss nan
Epoch 1500, Loss nan
Epoch 2000, Loss nan
Epoch 2500, Loss nan
Epoch 3000, Loss nan
Epoch 3500, Loss nan
Epoch 4000, Loss nan
Epoch 4500, Loss nan
Epoch 5000, Loss nan
Learning Rate: 0.001
Epoch 500, Loss nan
Epoch 1000, Loss nan
Epoch 1500, Loss nan
Epoch 2000, Loss nan
Epoch 2500, Loss nan
Epoch 3000, Loss nan
Epoch 3500, Loss nan
Epoch 4000, Loss nan
Epoch 4500, Loss nan
Epoch 5000, Loss nan
Learning Rate: 0.0001
Epoch 500, Loss 10.708596
Epoch 1000, Loss 8.642083
Epoch 1500, Loss 7.171005
Epoch 2000, Loss 6.123478
Epoch 2500, Loss 5.377227
Epoch 3000, Loss 4.845286
Epoch 3500, Loss 4.465788
Epoch 4000, Loss 4.194724
Epoch 4500, Loss 4.000802
Epoch 5000, Loss 3.861744


In [125]:
lin_params = torch.tensor([1.0, 0.0], requires_grad=True)
learning_rate = 0.0001
optimizer = optim.SGD([lin_params], lr=learning_rate)
print(f'Linear model with LR={learning_rate}')
lin_train_params, lin_train_loss = lin_training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = lin_params,
    t_u = t_un,
    t_c = t_c)

Linear model with LR=0.0001
Epoch 500, Loss 29.505890
Epoch 1000, Loss 28.943773
Epoch 1500, Loss 28.505281
Epoch 2000, Loss 28.074451
Epoch 2500, Loss 27.650877
Epoch 3000, Loss 27.234444
Epoch 3500, Loss 26.825020
Epoch 4000, Loss 26.422493
Epoch 4500, Loss 26.026745
Epoch 5000, Loss 25.637672
